<?php

namespace Fd\ActoPublicoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LicenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciaRepository extends EntityRepository
{
}
