<?php

namespace Fd\ActoPublicoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogActoPublicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogActoPublicoRepository extends EntityRepository
{
    public function count(){
        $dql = "select count(l.id) from ActoPublicoBundle:LogActoPublico l";
        return $this->getEntityManager()->createQuery($dql)->getSingleScalarResult();
    }
    public function truncar(){
        $q = $this->_em->createQuery('delete from '.$this->_entityName);
        $numDeleted = $q->execute();
        return;
    }
    
}
