<?php

namespace Fd\ActoPublicoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResumenMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumenMediaRepository extends EntityRepository {

    public function truncar() {
        $q = $this->_em->createQuery('delete from ' . $this->_entityName);
        $numDeleted = $q->execute();
        return;
    }

    /**
     * devuelve un array con los nombres de los cargos y las cantidades vacantes
     */
    public function cargosVacantes() {

        $dql = "select rm.cargo as cargo, count(rm.cargo) as cantidad, sum(rm.cantidad_horas) as horas, rm.slug_cargo 
            from ActoPublicoBundle:ResumenMedia rm 
            group by rm.cargo
            order by cantidad desc";

        return $this->_em
                        ->createQuery($dql)
                        ->execute();
    }

    public function cargosVacantesSeleccionados($slug_cargo) {

        $q = $this->createQueryBuilder('rm')
                ->select(array(
                    'rm.cargo as cargo',
                    'count(rm.establecimiento) as cantidad',
                    'sum(rm.cantidad_horas) as horas',
                    'rm.slug_cargo as slug',
                    'rm.establecimiento as establecimiento',
                ))
                ->where('rm.slug_cargo = ?1')
                ->groupBy('rm.establecimiento')
                ->orderBy('cantidad', 'DESC')
        ;
        $q->setParameter(1, $slug_cargo);

        return $q->getQuery()
                        ->getResult()
        ;
    }

    /**
     * selecciona el cargo más antiguo de todos
     */
    public function mas_antiguo() {

        $q = $this->createQueryBuilder('rm')
                ->select('rm')
                ->orderBy('rm.fecha_iniciacion', 'ASC')
        ;
        $q->setMaxResults( 1 );
        
        return $q->getQuery()
                        ->getSingleResult()
        ;
    }

}
