phpunit -c app/ src/Fd/EstablecimientoBundle/Tests/Controller/EstablecimientoControllerTest.php
phpunit -c app/ src/Fd/EstablecimientoBundle/Tests/Controller/UnidadEducativaControllerTest.php
phpunit -c app/ src/Fd/EstablecimientoBundle/Tests/Controller/UnidadOfertaControllerTest.php
phpunit -c app/ src/Fd/OfertaEducativaBundle/Tests/Controller/CarreraControllerTest.php
phpunit -c app/ src/Fd/OfertaEducativaBundle/Tests/Controller/NormaControllerTest.php
phpunit -c app/ src/Fd/OfertaEducativaBundle/Tests/Form/Handler/CarreraFormHandlerTest.php
phpunit -c app/ src/Fd/OfertaEducativaBundle/Tests/Model/CarreraManagerTest.php
phpunit -c app/ src/Fd/EstablecimientoBundle/Tests/Repository/EstablecimientoRepositoryTest.php
phpunit -c app/ src/Fd/OfertaEducativaBundle/Tests/Repository/CarreraRepositoryTest.php
