<?php

namespace Fd\TablaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoAutoridadRepository extends EntityRepository {

    public function qyAllOrdenado($campo) {
        return $this->createQueryBuilder('c')
                        ->orderBy('c.' . $campo)
                        ->getQuery();
    }

    public function findAllOrdenado($campo) {
        return $this->qyAllOrdenado($campo)->getResult();
    }

}