<?php

namespace Fd\TablaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fd\EstablecimientoBundle\Model\DatosAChoiceVisitadorInterface;
use Fd\EstablecimientoBundle\Model\DatosAChoiceVisitadoInterface;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends EntityRepository implements DatosAChoiceVisitadoInterface {

    public function qyAllOrdenado() {
        return $this->createQueryBuilder('cg')
                        ->orderBy('cg.nombre');
    }

    public function findAllOrdenado() {
        return $this->findear($this->qyAllOrdenado());
    }

    /**
     * dado un querybuilder devuelve los resultados de la consulta
     */
    public function findear($qb) {
        return $qb->getQuery()->getResult();
    }

    /*     * ****************************************
     * HASTA ACA
     * *********************************************
     * *********************************************
     * *********************************************
     * *********************************************
     * *********************************************
     * *********************************************
     * *********************************************
     */

    /**
     * Es visitado para pasar los datos de una Collection a un array determinado
     * el findAllORdenado pasa a un array con un cierto formato
     * 
     * @param DatosAChoiceVisitadorInterface $visitador
     * @return type
     */
    public function acceptDatosAChoice(DatosAChoiceVisitadorInterface $visitador) {
        return $visitador->visitCargo($this);
        ;
    }

}
