<?php

namespace Fd\TablaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCarreraRepository extends EntityRepository
{
//    public function qbAll(){
//        return $this->_em->createQueryBuilder('ec');
//    }
}