<?php

namespace Fd\TablaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fd\TablaBundle\Entity\TipoInstancia;

/**
 * TipoInstanciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInstanciaRepository extends EntityRepository {

    public function qbTodos() {
        return $this->createQueryBuilder('t');
    }
    public function qbTodosOrdenado(){
        return $this->qbTodos()->orderBy('t.codigo');
    }
    public function qyTodosOrdenado(){
        return $this->qbTodosOrdenado()->getQuery();
    }
    public function findAllOrdenado(){
        return $this->createQueryBuilder('t')->orderBy('t.codigo')->getQuery()->getResult();
    }

}