<?php

namespace Fd\TablaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoRepository extends EntityRepository {

    /**
     * devuelve arraycollection de objetos turno ordenador por campo orden
     * @return type
     */
    public function qbOrdenado() {
        return $this->createQueryBuilder('t')
                        ->orderBy('t.orden');
    }

}
