<?php

namespace Fd\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortadaRepository extends EntityRepository {

    public function qbAllOrdenado($campo = null) {
        $qb = $this->createQueryBuilder('p')
                ->orderBy((!$campo) ? 'p.tabla' : 'p.' . $campo );
        return $qb;
    }

    public function qyAllOrdenado($campo = null) {
        return $this->qbAllOrdenado($campo)
                ->getQuery();
    }

    public function findAllOrdenado($campo = null) {
        return $this->qyAllOrdenado($campo)
                ->getResult();
    }

}