<?php

namespace Fd\OfertaEducativaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fd\EstablecimientoBundle\Entity\Respuesta;
use Fd\OfertaEducativaBundle\Entity\OfertaEducativa;
use Fd\EstablecimientoBundle\Entity\UnidadOferta;
use Fd\TablaBundle\Entity\EstadoCarrera;
use Fd\OfertaEducativaBundle\Entity\CarreraEstadoValidez;

/**
 * CarreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarreraRepository extends EntityRepository {

    /**
     * 25/2/15 modificado para la migracion de localizaciones
     * 
     * dado un establecimeinto devuelve objetos de tipo carrera de las carreras del mismo, sin localizar
     * 
     * @return type resultados objetos carrera
     */
    public function findCarrerasPorEstablecimiento($establecimiento) {
        
        /** aca hay que pasar por las localizaciones de cada carrera y eliminar los casos de carreras que se den en más de una localización
         * para qu no queden repetidas
         */
        
        $dql = "select c
            from OfertaEducativaBundle:Carrera c 
            join c.oferta o 
            join o.unidades u
            join u.unidades ue
            join ue.establecimiento e 
            where e.id = :establecimiento";
        $q = $this->_em->createQuery($dql);
        $q->setParameter('establecimiento', $establecimiento);
        return $q->getResult();
    }

    public function qbAllOrdenado($campo){
        return $this->createQueryBuilder('c')
                        ->orderBy('c.' . $campo);
    }
    public function qyAllOrdenado($campo) {
        return $this->qbAllOrdenado($campo)
                        ->getQuery();
    }

    /**
     * listado de carreras en estado activo ordenadas por nombre sin repetidos
     * @return type
     */
    public function qyResumido() {
        return $this->createQueryBuilder('c')
                        ->select(array(
                            'distinct c.nombre', 'f.codigo', 'c.id',
                        ))
                        ->innerJoin('c.estado', 'e')
                        ->innerJoin('c.formacion', 'f')
                        ->where('e.codigo = :codigo_estado')
                        ->groupBy('c.nombre')
                        ->orderBy('c.nombre')
                        ->setParameter('codigo_estado', 'ACT')
                        ->getQuery();
    }

    public function dqlActivas() {
        $x = $this->getEntityManager()->getReference('TablaBundle:EstadoCarrera', 1);
        $xx = $this->createQueryBuilder('c')
                ->where('c.estado = :estado');
        $xx->setParameter('estado', $x->getId());
        return $xx;
    }

    public function dqlActivasOrdenadas($campo) {
        return $this->dqlActivas()->orderBy('c.' . $campo);
    }

    public function qyActivasOrdenadas($campo) {
        return $this->dqlActivasOrdenadas($campo)->getQuery();
    }

    public function findActivasOrdenadas($campo) {
        return $this->qyActivasOrdenadas($campo)->getResult();
    }

    public function findAllOrdenado($campo) {
        return $this->qyAllOrdenado($campo)->getResult();
    }
    /**
     * Lista de carreras para un combo
     */
    public function combo($establecimiento = null) {
        if ($establecimiento) {
            return $this->findCarrerasPorEstablecimiento($establecimiento);
        };
        return $this->findAllOrdenado('nombre');
    }

}