<?php

namespace Fd\OfertaEducativaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaRepository extends EntityRepository {

    public function qbAll() {
        return $this->createQueryBuilder('dsc');
    }

    public function findAll() {

        return $this->findear($this->qyAll());
    }

    public function qbAllOrdenado() {

        return $this->qbAll()
                        ->orderBy('dsc.descripcion');
    }

    public function findAllOrdenado() {
        return $this->findear($this->qbAllOrdenado());
    }

    public function findear($qb) {
        return $qb->getQuery()->getResult();
    }

}
