<?php

namespace Fd\OfertaEducativaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fd\EstablecimientoBundle\Entity\Respuesta;

/**
 * OfertaEducativaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaEducativaRepository extends EntityRepository {

    /**
     * devuelve la lista de las ofertas educativas ordenadas por un campo de la superclase
     * @param type $campo
     * @return type
     */
    public function findAllOrdenadoPorNivel() {
        return $this->createQueryBuilder('oe')->join('oe.nivel', 'n')
                        ->orderBy('n.nombre')->getQuery()->getResult();
    }

    public function findCarreras() {
        return $this->createQueryBuilder('oe')
                        ->where('oe.tipo=:carrera')
                        ->getQuery()
                        ->setParameter('carrera', 'carrera')
                        ->getResult()
        ;
    }

}