<?php

namespace Fd\OfertaEducativaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Fd\EstablecimientoBundle\Entity\Respuesta;
use Fd\OfertaEducativaBundle\Entity\OfertaEducativa;
use Fd\EstablecimientoBundle\Entity\UnidadOferta;
use Fd\OfertaEducativaBundle\Entity\CarreraEstadoValidez;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TituloRepository extends EntityRepository {
}